database:
  dialect: mysql
  host: localhost
  port: 3309
  dbname: link-box
  username: testuser
  password: password
  migration: true

extension:
  master_generator: true
  cors_enabled: true
  security_enabled: true

log:
  request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status}

staticcontents:
  enabled: true

swagger:
  enabled: true
  path: /swagger/.*

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /swagger/.*
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
  admin_path:
    - /api/.*
