project_id = "link-box-stg-400005"
region = "asia-northeast1"
vpc_name = "link-box-vpc-stg"
vpc_access_connector_name = "link-box-connector-stg"
db_dinstance_name = "link-box-instance-stg"
cloud_run_name = "link-box-cloud-run-stg"